"""
Django settings for fiszki project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
import dj_database_url  # Biblioteka do obsługi bazy PostgreSQL (Neon)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Pobiera klucz ze zmiennych środowiskowych Rendera, a jak nie ma, to używa zapasowego (dla lokalnego dev)
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-zmien-mnie-na-produkcji-12345')

# SECURITY WARNING: don't run with debug turned on in production!
# Automatycznie wyłącza DEBUG, gdy strona jest na Renderze
DEBUG = 'RENDER' not in os.environ

# Pozwala na działanie na Renderze (onrender.com) i lokalnie
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- TWOJE APLIKACJE I DODATKI ---
    'corsheaders',  # Niezbędne, żeby React mógł gadać z Django
    'slowka',  # Twoja aplikacja
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # <--- TO MUSI BYĆ NA SAMEJ GÓRZE!
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Obsługa plików statycznych na Renderze
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fiszki.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fiszki.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Konfiguracja pod NEON.TECH (PostgreSQL)
# Jeśli link jest w zmiennych środowiskowych (na Renderze), użyje go.
# Jeśli nie (lokalnie), użyje tego wklejonego w 'default'.

DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://neondb_owner:npg_sfqktyOAWI50@ep-calm-resonance-agyyd59j-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require',
        conn_max_age=600,
        ssl_require=True
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# To jest ważne dla Rendera - tutaj będą zbierane pliki CSS/JS
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Włączamy kompresję plików statycznych (Whitenoise)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- KONFIGURACJA CORS (DLA REACTA) ---
# Tutaj wpisujesz adresy, które mogą łączyć się z Twoim API
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Twój React lokalnie
    "http://127.0.0.1:3000",  # Alternatywny localhost
    # "https://twoja-strona.web.app",    # <--- Odkomentuj i wpisz tu adres, jak wrzucisz Reacta na Firebase
]
