# Generated by Django 5.2.8 on 2025-11-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slowko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angielski', models.CharField(max_length=100)),
                ('polski', models.CharField(max_length=100)),
            ],
        ),
    ]
