# Generated by Django 5.2.8 on 2025-12-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slowka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slowko',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='slowko',
            name='kategoria',
            field=models.CharField(default='Ogólne', max_length=100),
        ),
        migrations.AddField(
            model_name='slowko',
            name='wymowa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slowko',
            name='angielski',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='slowko',
            name='polski',
            field=models.CharField(max_length=255),
        ),
    ]
